name: CI

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download


      - name: Run tests with coverage
        run: go test -v -cover ./...

      - name: Building
        run: go build -o myapp

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-binary
          path: myapp
